version: '3.8'

services:
  auth-service:
    build:
      context: ./auth
    ports:
      - "8081:8080"

  profile-service:
    build:
      context: ./profile
    ports:
      - "8082:8080"

  friend-service:
    build:
      context: ./friends
    ports:
      - "8083:8080"

  message-service:
    build:
      context: ./chats
    ports:
      - "8084:8080"

  notification-service:
    build:
      context: ./notifications
    ports:
      - "8085:8080"