version: '3.8'

services:
  auth-service:
    build:
      context: ./auth
    ports:
      - "8081:8080"

  profile-service:
    build:
      context: ./profile
    ports:
      - "8082:8080"

  message-service:
    build:
      context: ./chats
    ports:
      - "8082:8080"