// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteProfileIDFriendsTargetIDOKCode is the HTTP code returned for type DeleteProfileIDFriendsTargetIDOK
const DeleteProfileIDFriendsTargetIDOKCode int = 200

/*
DeleteProfileIDFriendsTargetIDOK Friend removed

swagger:response deleteProfileIdFriendsTargetIdOK
*/
type DeleteProfileIDFriendsTargetIDOK struct {
}

// NewDeleteProfileIDFriendsTargetIDOK creates DeleteProfileIDFriendsTargetIDOK with default headers values
func NewDeleteProfileIDFriendsTargetIDOK() *DeleteProfileIDFriendsTargetIDOK {

	return &DeleteProfileIDFriendsTargetIDOK{}
}

// WriteResponse to the client
func (o *DeleteProfileIDFriendsTargetIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteProfileIDFriendsTargetIDNotFoundCode is the HTTP code returned for type DeleteProfileIDFriendsTargetIDNotFound
const DeleteProfileIDFriendsTargetIDNotFoundCode int = 404

/*
DeleteProfileIDFriendsTargetIDNotFound Friend not found

swagger:response deleteProfileIdFriendsTargetIdNotFound
*/
type DeleteProfileIDFriendsTargetIDNotFound struct {
}

// NewDeleteProfileIDFriendsTargetIDNotFound creates DeleteProfileIDFriendsTargetIDNotFound with default headers values
func NewDeleteProfileIDFriendsTargetIDNotFound() *DeleteProfileIDFriendsTargetIDNotFound {

	return &DeleteProfileIDFriendsTargetIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteProfileIDFriendsTargetIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
