// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProfileIDFriendsHandlerFunc turns a function with the right signature into a get profile ID friends handler
type GetProfileIDFriendsHandlerFunc func(GetProfileIDFriendsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProfileIDFriendsHandlerFunc) Handle(params GetProfileIDFriendsParams) middleware.Responder {
	return fn(params)
}

// GetProfileIDFriendsHandler interface for that can handle valid get profile ID friends params
type GetProfileIDFriendsHandler interface {
	Handle(GetProfileIDFriendsParams) middleware.Responder
}

// NewGetProfileIDFriends creates a new http.Handler for the get profile ID friends operation
func NewGetProfileIDFriends(ctx *middleware.Context, handler GetProfileIDFriendsHandler) *GetProfileIDFriends {
	return &GetProfileIDFriends{Context: ctx, Handler: handler}
}

/*
	GetProfileIDFriends swagger:route GET /profile/{id}/friends getProfileIdFriends

Get friend list by profile ID
*/
type GetProfileIDFriends struct {
	Context *middleware.Context
	Handler GetProfileIDFriendsHandler
}

func (o *GetProfileIDFriends) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProfileIDFriendsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
