// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetChatsOKCode is the HTTP code returned for type GetChatsOK
const GetChatsOKCode int = 200

/*
GetChatsOK A list of chats

swagger:response getChatsOK
*/
type GetChatsOK struct {

	/*
	  In: Body
	*/
	Payload []*GetChatsOKBodyItems0 `json:"body,omitempty"`
}

// NewGetChatsOK creates GetChatsOK with default headers values
func NewGetChatsOK() *GetChatsOK {

	return &GetChatsOK{}
}

// WithPayload adds the payload to the get chats o k response
func (o *GetChatsOK) WithPayload(payload []*GetChatsOKBodyItems0) *GetChatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get chats o k response
func (o *GetChatsOK) SetPayload(payload []*GetChatsOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetChatsOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
