// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetProfileIDHandlerFunc turns a function with the right signature into a get profile ID handler
type GetProfileIDHandlerFunc func(GetProfileIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProfileIDHandlerFunc) Handle(params GetProfileIDParams) middleware.Responder {
	return fn(params)
}

// GetProfileIDHandler interface for that can handle valid get profile ID params
type GetProfileIDHandler interface {
	Handle(GetProfileIDParams) middleware.Responder
}

// NewGetProfileID creates a new http.Handler for the get profile ID operation
func NewGetProfileID(ctx *middleware.Context, handler GetProfileIDHandler) *GetProfileID {
	return &GetProfileID{Context: ctx, Handler: handler}
}

/*
	GetProfileID swagger:route GET /profile/{id} getProfileId

Get profile by ID
*/
type GetProfileID struct {
	Context *middleware.Context
	Handler GetProfileIDHandler
}

func (o *GetProfileID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProfileIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetProfileIDOKBody get profile ID o k body
//
// swagger:model GetProfileIDOKBody
type GetProfileIDOKBody struct {

	// email
	Email string `json:"email,omitempty"`

	// friends
	Friends []string `json:"friends"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this get profile ID o k body
func (o *GetProfileIDOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get profile ID o k body based on context it is used
func (o *GetProfileIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetProfileIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetProfileIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetProfileIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
