// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetProfileIDOKCode is the HTTP code returned for type GetProfileIDOK
const GetProfileIDOKCode int = 200

/*
GetProfileIDOK Profile data

swagger:response getProfileIdOK
*/
type GetProfileIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetProfileIDOKBody `json:"body,omitempty"`
}

// NewGetProfileIDOK creates GetProfileIDOK with default headers values
func NewGetProfileIDOK() *GetProfileIDOK {

	return &GetProfileIDOK{}
}

// WithPayload adds the payload to the get profile Id o k response
func (o *GetProfileIDOK) WithPayload(payload *GetProfileIDOKBody) *GetProfileIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get profile Id o k response
func (o *GetProfileIDOK) SetPayload(payload *GetProfileIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProfileIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProfileIDNotFoundCode is the HTTP code returned for type GetProfileIDNotFound
const GetProfileIDNotFoundCode int = 404

/*
GetProfileIDNotFound Profile not found

swagger:response getProfileIdNotFound
*/
type GetProfileIDNotFound struct {
}

// NewGetProfileIDNotFound creates GetProfileIDNotFound with default headers values
func NewGetProfileIDNotFound() *GetProfileIDNotFound {

	return &GetProfileIDNotFound{}
}

// WriteResponse to the client
func (o *GetProfileIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
