// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchProfileIDFriendRequestsTargetIDOKCode is the HTTP code returned for type PatchProfileIDFriendRequestsTargetIDOK
const PatchProfileIDFriendRequestsTargetIDOKCode int = 200

/*
PatchProfileIDFriendRequestsTargetIDOK Friend request processed

swagger:response patchProfileIdFriendRequestsTargetIdOK
*/
type PatchProfileIDFriendRequestsTargetIDOK struct {
}

// NewPatchProfileIDFriendRequestsTargetIDOK creates PatchProfileIDFriendRequestsTargetIDOK with default headers values
func NewPatchProfileIDFriendRequestsTargetIDOK() *PatchProfileIDFriendRequestsTargetIDOK {

	return &PatchProfileIDFriendRequestsTargetIDOK{}
}

// WriteResponse to the client
func (o *PatchProfileIDFriendRequestsTargetIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PatchProfileIDFriendRequestsTargetIDBadRequestCode is the HTTP code returned for type PatchProfileIDFriendRequestsTargetIDBadRequest
const PatchProfileIDFriendRequestsTargetIDBadRequestCode int = 400

/*
PatchProfileIDFriendRequestsTargetIDBadRequest Invalid action

swagger:response patchProfileIdFriendRequestsTargetIdBadRequest
*/
type PatchProfileIDFriendRequestsTargetIDBadRequest struct {
}

// NewPatchProfileIDFriendRequestsTargetIDBadRequest creates PatchProfileIDFriendRequestsTargetIDBadRequest with default headers values
func NewPatchProfileIDFriendRequestsTargetIDBadRequest() *PatchProfileIDFriendRequestsTargetIDBadRequest {

	return &PatchProfileIDFriendRequestsTargetIDBadRequest{}
}

// WriteResponse to the client
func (o *PatchProfileIDFriendRequestsTargetIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PatchProfileIDFriendRequestsTargetIDNotFoundCode is the HTTP code returned for type PatchProfileIDFriendRequestsTargetIDNotFound
const PatchProfileIDFriendRequestsTargetIDNotFoundCode int = 404

/*
PatchProfileIDFriendRequestsTargetIDNotFound Request not found

swagger:response patchProfileIdFriendRequestsTargetIdNotFound
*/
type PatchProfileIDFriendRequestsTargetIDNotFound struct {
}

// NewPatchProfileIDFriendRequestsTargetIDNotFound creates PatchProfileIDFriendRequestsTargetIDNotFound with default headers values
func NewPatchProfileIDFriendRequestsTargetIDNotFound() *PatchProfileIDFriendRequestsTargetIDNotFound {

	return &PatchProfileIDFriendRequestsTargetIDNotFound{}
}

// WriteResponse to the client
func (o *PatchProfileIDFriendRequestsTargetIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
