// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchProfileIDFriendRequestsTargetIDHandlerFunc turns a function with the right signature into a patch profile ID friend requests target ID handler
type PatchProfileIDFriendRequestsTargetIDHandlerFunc func(PatchProfileIDFriendRequestsTargetIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchProfileIDFriendRequestsTargetIDHandlerFunc) Handle(params PatchProfileIDFriendRequestsTargetIDParams) middleware.Responder {
	return fn(params)
}

// PatchProfileIDFriendRequestsTargetIDHandler interface for that can handle valid patch profile ID friend requests target ID params
type PatchProfileIDFriendRequestsTargetIDHandler interface {
	Handle(PatchProfileIDFriendRequestsTargetIDParams) middleware.Responder
}

// NewPatchProfileIDFriendRequestsTargetID creates a new http.Handler for the patch profile ID friend requests target ID operation
func NewPatchProfileIDFriendRequestsTargetID(ctx *middleware.Context, handler PatchProfileIDFriendRequestsTargetIDHandler) *PatchProfileIDFriendRequestsTargetID {
	return &PatchProfileIDFriendRequestsTargetID{Context: ctx, Handler: handler}
}

/*
	PatchProfileIDFriendRequestsTargetID swagger:route PATCH /profile/{id}/friend-requests/{targetId} patchProfileIdFriendRequestsTargetId

Accept or reject friend request
*/
type PatchProfileIDFriendRequestsTargetID struct {
	Context *middleware.Context
	Handler PatchProfileIDFriendRequestsTargetIDHandler
}

func (o *PatchProfileIDFriendRequestsTargetID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchProfileIDFriendRequestsTargetIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
