// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostProfileIDFriendRequestsOKCode is the HTTP code returned for type PostProfileIDFriendRequestsOK
const PostProfileIDFriendRequestsOKCode int = 200

/*
PostProfileIDFriendRequestsOK Friend request sent

swagger:response postProfileIdFriendRequestsOK
*/
type PostProfileIDFriendRequestsOK struct {
}

// NewPostProfileIDFriendRequestsOK creates PostProfileIDFriendRequestsOK with default headers values
func NewPostProfileIDFriendRequestsOK() *PostProfileIDFriendRequestsOK {

	return &PostProfileIDFriendRequestsOK{}
}

// WriteResponse to the client
func (o *PostProfileIDFriendRequestsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostProfileIDFriendRequestsBadRequestCode is the HTTP code returned for type PostProfileIDFriendRequestsBadRequest
const PostProfileIDFriendRequestsBadRequestCode int = 400

/*
PostProfileIDFriendRequestsBadRequest Invalid input

swagger:response postProfileIdFriendRequestsBadRequest
*/
type PostProfileIDFriendRequestsBadRequest struct {
}

// NewPostProfileIDFriendRequestsBadRequest creates PostProfileIDFriendRequestsBadRequest with default headers values
func NewPostProfileIDFriendRequestsBadRequest() *PostProfileIDFriendRequestsBadRequest {

	return &PostProfileIDFriendRequestsBadRequest{}
}

// WriteResponse to the client
func (o *PostProfileIDFriendRequestsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
