// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostChatsChatIDMessagesCreatedCode is the HTTP code returned for type PostChatsChatIDMessagesCreated
const PostChatsChatIDMessagesCreatedCode int = 201

/*
PostChatsChatIDMessagesCreated Message created

swagger:response postChatsChatIdMessagesCreated
*/
type PostChatsChatIDMessagesCreated struct {
}

// NewPostChatsChatIDMessagesCreated creates PostChatsChatIDMessagesCreated with default headers values
func NewPostChatsChatIDMessagesCreated() *PostChatsChatIDMessagesCreated {

	return &PostChatsChatIDMessagesCreated{}
}

// WriteResponse to the client
func (o *PostChatsChatIDMessagesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
