// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostProfileIDFriendRequestsHandlerFunc turns a function with the right signature into a post profile ID friend requests handler
type PostProfileIDFriendRequestsHandlerFunc func(PostProfileIDFriendRequestsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostProfileIDFriendRequestsHandlerFunc) Handle(params PostProfileIDFriendRequestsParams) middleware.Responder {
	return fn(params)
}

// PostProfileIDFriendRequestsHandler interface for that can handle valid post profile ID friend requests params
type PostProfileIDFriendRequestsHandler interface {
	Handle(PostProfileIDFriendRequestsParams) middleware.Responder
}

// NewPostProfileIDFriendRequests creates a new http.Handler for the post profile ID friend requests operation
func NewPostProfileIDFriendRequests(ctx *middleware.Context, handler PostProfileIDFriendRequestsHandler) *PostProfileIDFriendRequests {
	return &PostProfileIDFriendRequests{Context: ctx, Handler: handler}
}

/*
	PostProfileIDFriendRequests swagger:route POST /profile/{id}/friend-requests postProfileIdFriendRequests

Send friend request
*/
type PostProfileIDFriendRequests struct {
	Context *middleware.Context
	Handler PostProfileIDFriendRequestsHandler
}

func (o *PostProfileIDFriendRequests) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostProfileIDFriendRequestsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostProfileIDFriendRequestsBody post profile ID friend requests body
//
// swagger:model PostProfileIDFriendRequestsBody
type PostProfileIDFriendRequestsBody struct {

	// target Id
	TargetID string `json:"targetId,omitempty"`
}

// Validate validates this post profile ID friend requests body
func (o *PostProfileIDFriendRequestsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post profile ID friend requests body based on context it is used
func (o *PostProfileIDFriendRequestsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostProfileIDFriendRequestsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostProfileIDFriendRequestsBody) UnmarshalBinary(b []byte) error {
	var res PostProfileIDFriendRequestsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
