// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutProfileIDHandlerFunc turns a function with the right signature into a put profile ID handler
type PutProfileIDHandlerFunc func(PutProfileIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutProfileIDHandlerFunc) Handle(params PutProfileIDParams) middleware.Responder {
	return fn(params)
}

// PutProfileIDHandler interface for that can handle valid put profile ID params
type PutProfileIDHandler interface {
	Handle(PutProfileIDParams) middleware.Responder
}

// NewPutProfileID creates a new http.Handler for the put profile ID operation
func NewPutProfileID(ctx *middleware.Context, handler PutProfileIDHandler) *PutProfileID {
	return &PutProfileID{Context: ctx, Handler: handler}
}

/*
	PutProfileID swagger:route PUT /profile/{id} putProfileId

Update profile
*/
type PutProfileID struct {
	Context *middleware.Context
	Handler PutProfileIDHandler
}

func (o *PutProfileID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutProfileIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutProfileIDBody put profile ID body
//
// swagger:model PutProfileIDBody
type PutProfileIDBody struct {

	// email
	Email string `json:"email,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this put profile ID body
func (o *PutProfileIDBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put profile ID body based on context it is used
func (o *PutProfileIDBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutProfileIDBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutProfileIDBody) UnmarshalBinary(b []byte) error {
	var res PutProfileIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
