// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutProfileIDOKCode is the HTTP code returned for type PutProfileIDOK
const PutProfileIDOKCode int = 200

/*
PutProfileIDOK Profile updated

swagger:response putProfileIdOK
*/
type PutProfileIDOK struct {
}

// NewPutProfileIDOK creates PutProfileIDOK with default headers values
func NewPutProfileIDOK() *PutProfileIDOK {

	return &PutProfileIDOK{}
}

// WriteResponse to the client
func (o *PutProfileIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutProfileIDBadRequestCode is the HTTP code returned for type PutProfileIDBadRequest
const PutProfileIDBadRequestCode int = 400

/*
PutProfileIDBadRequest Invalid input

swagger:response putProfileIdBadRequest
*/
type PutProfileIDBadRequest struct {
}

// NewPutProfileIDBadRequest creates PutProfileIDBadRequest with default headers values
func NewPutProfileIDBadRequest() *PutProfileIDBadRequest {

	return &PutProfileIDBadRequest{}
}

// WriteResponse to the client
func (o *PutProfileIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
