swagger: "2.0"
info:
  title: Chat Service API
  description: API for managing chats and messages
  version: 1.0.0
paths:
  /chats:
    get:
      summary: Get list of chats
      responses:
        200:
          description: A list of chats
          schema:
            type: array
            items:
              type: object
              properties:
                chatId:
                  type: string
                participants:
                  type: array
                  items:
                    type: string
  /chats/{chatId}/messages:
    post:
      summary: Add a message to a chat
      parameters:
        - name: chatId
          in: path
          required: true
          type: string
        - in: body
          name: message
          description: Message data
          required: true
          schema:
            type: object
            properties:
              senderId:
                type: string
              message:
                type: string
      responses:
        201:
          description: Message created
